<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    
<h3>Política de Privacidade Wrahgles</h3>
<div class="term-1">
    <p>O Wrahgles tem o compromisso de proteger sua privacidade e de cumprir as leis aplicáveis no que se refere à proteção de dados e privacidade. Esperamos que esta Política de Privacidade ("Política") ajude-o a entender que tipo de informações coletamos com relação a nossos serviços e como processamos estas informações. Para fins desta Política, a expressão "dados pessoais" significa informações relacionadas a um indivíduo identificado ou identificável (isto é, uma pessoa física). "Wrahgles" refere-se à Wrahgles S/A, incluindo suas afiliadas (também designadas como "nós" ou "nosso").</p>
    <p>Esta Política aplica-se aos dados pessoais coletados em conexão com os serviços oferecidos pelo Wrahgles ou através de outras interações conosco, quando houver um link ou outro tipo de referência a esta Política, por exemplo, com relação a nossos equipamentos e acessórios, websites (incluindo websites de internet móvel) e outros tipos de serviços oferecidos pelo Wrahgles, normalmente em formato web, além de outros serviços como atendimento ao cliente e serviços de garantia.</p>
    <p>Podemos fornecer informações adicionais ou complementares com relação a um serviço específico do Wrahgles. Estas informações prevalecerão sobre a Política na medida em que houver qualquer conflito. Nossos produtos ou serviços podem conter links para websites de outras empresas e serviços de terceiros que mantêm suas próprias políticas de privacidade. Recomendamos a leitura das políticas de privacidade desses serviços. O Wrahgles não se responsabiliza pelas práticas de privacidade ou conteúdo desses serviços.</p>
    <p><strong>Ao utilizar este website e/ou ao enviar dados pessoais para o Wrahgles, você está demonstrando expressamente sua concordância em relação ao processamento de seus dados pessoais de acordo com os termos desta Política. Se você não concorda com esta Política, não use este website ou não forneça dados pessoais ao Wrahgles.</strong></p>
    <h4>Dados que coletamos</h4>
    <p>Normalmente coletamos seus dados pessoais para você ter acesso aos serviços, utiliza ou registra-se em nossos serviços, participa de uma promoção ou campanha, ou quando interage conosco de qualquer outra maneira. Buscamos coletar seus dados pessoais somente com seu conhecimento ou autorização. Abaixo mostramos alguns exemplos das categorias de dados coletados:</p>
    <ul class="list-none">
        <li><strong>Informações técnicas:</strong> Na maioria das vezes é possível visitar nossos websites sem que você precise nos informar quem é. No entanto, algumas informações técnicas são normalmente coletadas como parte do uso que você faz de nossos serviços. Estas informações incluem, por exemplo, seu endereço IP, número de acessos, website que o remeteu à nossa página, páginas visitadas, links utilizados, banners e outros conteúdos visualizados, informações sobre seus equipamentos e outras informações técnicas similares que seu navegador fornece ou que possam ser coletadas com relação a alguns produtos e serviços. Ao utilizar nossos serviços ou interagir conosco através de redes de telecomunicações, algumas informações adicionais como número de seu celular podem ser transmitidas pela operadora de telecomunicações de acordo com os padrões desta comunicação. Consulte a seção "<span>Uso de cookies e web beacons</span>" abaixo.</li>
        <li><strong>Informações fornecidas por você:</strong> Ao se registrar em nossos serviços, participar de uma promoção ou de outra forma interagir conosco, podemos solicitar que sejam fornecidas informações como seu nome, endereço de email, endereço, assim como nomes de usuário, senhas e outras credenciais similares adotadas para autenticar usuários e validar suas ações, ou que possam ser necessárias para que os serviços solicitados sejam fornecidos, ou ainda para nos comunicarmos com você. Podemos coletar informações demográficas como sua idade, sexo, código postal e preferências de idioma. Também podemos coletar outras informações fornecidas por você, como suas autorizações, preferências, feedback e informações similares fornecidas por você. Note que algumas informações não identificáveis coletadas podem vir a se tornar identificáveis quando você fornecer seus dados pessoais. Também podemos vir a utilizar, nos termos da lei aplicável, alguns dados pessoais disponibilizados por empresas de mala direta e outras fontes de acesso público. Alguns de nossos serviços podem permitir que você envie informações sobre terceiros, por exemplo, se você realizar um cadastro de um estabelecimento no qual gosta muito de frequentar, como: restaurantes, bares, shoppings, dentre outros.</li>
        <li><strong>Suas transações conosco:</strong> Coletamos ou pedimos informações relacionadas ao uso de nossos produtos e/ou serviços e suas outras interações conosco. Essas informações podem incluir, por exemplo, detalhes sobre solicitações que você tenha feito e serviços utilizados (incluindo detalhes sobre localidades), informações de contratos celebrados entre você e o Wrahgles, registros de contatos e comunicações, informações e detalhes referentes aos dados fornecidos por você e outras informações transacionais. De acordo com a legislação aplicável, podemos gravar suas comunicações com nosso serviço ou outros pontos de contato. Alguns serviços podem envolver o uso de seus dados de localização. No entanto, o uso de seus dados de localização para estes serviços estará sujeito ao seu consentimento.</li>                        
    </ul>
    <p></p>
    <h4>Objetivos para os quais processamos seus dados pessoais</h4>
    <p>O Wrahgles processa seus dados pessoais para os fins descritos nesta Política e/ou em qualquer informação de privacidade específica dos serviços. Note que um ou mais objetivos podem ser aplicáveis simultaneamente:</p>
    <ul class="list-none">
        <li><strong>Prestação de serviços:</strong> Podemos usar seus dados pessoais para atender suas solicitações, processar seu pedido ou como seja necessário de alguma outra forma para cumprir ou executar o contrato entre você e o Wrahgles, para garantir a funcionalidade e a segurança de nossos produtos e serviços, para identificá-lo e evitar e investigar casos de fraude e outros usos não-autorizados.</li>
        <li><strong>Desenvolvimento de serviços:</strong> Podemos utilizar seus dados pessoais para desenvolver nossos serviços. No entanto, na maioria das vezes usamos apenas informações estatísticas e agregadas no desenvolvimento de serviços. Também podemos usar seus dados pessoais para personalizar nossa oferta e prestar serviços que sejam de maior relevância para você, por exemplo, fazendo recomendações e exibindo conteúdo e anúncios customizados em nossos websites. Podemos combinar os dados pessoais coletados com relação a seu uso de um serviço específico do Wrahgles com outros dados pessoais que o Wrahgles possa ter sobre você, exceto quando estes dados pessoais foram coletados para outro fim. Podemos criar informações estatísticas e agregadas com base em seus dados pessoais.</li>
        <li><strong>Comunicações com você e ações de marketing:</strong> Podemos utilizar seus dados pessoais para nos comunicarmos com você, por exemplo, para fornecer informações relacionadas a nossos serviços que você usa ou para contatá-lo para realização de pesquisas de satisfação do consumidor. Podemos utilizar seus dados pessoais para fins de marketing ou pesquisa, por exemplo, para realizar pesquisas de mercado, e, ainda, nos termos da lei aplicável, podemos contatá-lo para informar-lhe sobre novos serviços ou promoções. Além disso, alguns de nossos serviços podem ser utilizados para promover produtos e serviços de outras empresas. Entretanto, o Wrahgles não divulgará seus dados pessoais a essas empresas, nem a quaisquer outras empresas para fins de marketing sem o seu consentimento prévio.</li>
    </ul>
    <p></p>
    <h4>Compartilhando seus dados pessoais</h4>
    <p>De forma geral não vendemos, arrendamos, alugamos ou divulgamos de qualquer outra forma seus dados pessoais a terceiros, exceto nos termos estabelecidos abaixo:</p>
    <ul class="list-none">
        <li><strong>Consentimento:</strong> Podemos compartilhar seus dados pessoais se tivermos o seu consentimento para fazê-lo. Alguns serviços podem incluir o compartilhamento de dados pessoais com outros usuários do serviço, por exemplo, serviços onde os usuários publicam seu próprio conteúdo ou comunidades de usuários Wrahgles.</li>
        <li><strong>Empresas Wrahgles e terceiros autorizados:</strong> Podemos compartilhar seus dados pessoais com outras empresas Wrahgles ou terceiros autorizados que fazem o processamento de seus dados pessoais para o Wrahgles para os fins descritos nesta Política. Essas empresas não têm permissão para utilizar seus dados pessoais para quaisquer outros fins, e exigimos que atuem de forma absolutamente consistente com esta Política e que adotem medidas de segurança apropriadas para proteção de seus dados pessoais.</li>
        <li><strong>Transferências internacionais:</strong> Nossos serviços podem ser fornecidos através do uso de recursos e servidores localizados em diversos países no mundo. Assim, seus dados pessoais podem ser transferidos por fronteiras internacionais, fora do país onde você usa nossos serviços, incluindo países que tenham regras diferentes sobre proteção de dados, como por exemplo os Estados Unidos da América. Nesses casos tomaremos as medidas necessárias para garantir a proteção adequada de seus dados pessoais, conforme estabelecido na legislação aplicável, por exemplo através do uso de contratos padrão aprovados pelas autoridades competentes (quando necessário) e exigindo o uso de outras medidas de natureza organizacional e técnica apropriadas para segurança de informações.</li>
        <li><strong>Divulgações obrigatórias:</strong> Podemos ser obrigados por lei a divulgar seus dados pessoais a determinadas autoridades e terceiros, por exemplo, para a polícia em países onde operamos ou onde operam terceiros atuando em nosso nome. Também podemos divulgar e de qualquer outra forma processar seus dados pessoais de acordo com a lei aplicável para defender os interesses legítimos do Loucalza, por exemplo, em processos de natureza cível ou penal.</li>
        <li><strong>Fusões e aquisições:</strong> Se decidirmos vender, comprar, realizar uma fusão, ou de alguma outra forma reorganizar nossas operações comerciais em determinados países, isso pode incluir a divulgação de dados pessoais a possíveis ou reais compradores e seus consultores, ou o recebimento de dados pessoais dos vendedores e seus consultores.</li>
    </ul>
    <p></p>
    <h4>Qualidade de dados</h4>
    <p>Adotamos as medidas razoáveis para manter os dados pessoais em nosso poder atualizados e exatos e excluir dados pessoais incorretos, desatualizados ou desnecessários.</p>
    <p>Considerando que alguns serviços do Wrahgles permitem que você gerencie seu perfil, incentivamos o acesso a seus dados pessoais de tempos em tempos para garantir que estejam corretos e atualizados. <strong>Lembre-se de que é sua responsabilidade</strong> nos fornecer informações corretas assim como atualizar os dados pessoais fornecidos por você caso haja qualquer alteração nos mesmos.</p>
    <h4>Segurança</h4>
    <p>Embora sempre haja riscos associados ao fornecimento de dados pessoais, sejam pessoalmente, pelo telefone, pela Internet ou por quaisquer outros meios, e embora não haja qualquer tecnologia totalmente segura e à prova de <em>hackers</em> ou <em>tampers</em>, o Wrahgles as adota medidas de segurança da informação organizacionais e técnicas apropriadas para evitar e minimizar tais riscos.</p>
    <p>Estas medidas incluem, quando apropriado, o uso de firewalls, instalações seguras para o servidor, criptografia, implantação de processos e sistemas de gerenciamento de direitos de acesso apropriados, seleção criteriosa de processadores e outras medidas razoáveis do ponto de vista técnico e comercial para oferecer proteção apropriada aos seus dados pessoais contra uso ou divulgação não-autorizados. Quando apropriado, também podemos fazer cópias de backup e usar outros meios para evitar danos ou a destruição acidental de seus dados pessoais. Se uma parte específica do website do Wrahgles suportar transações online, adotaremos medidas de segurança de acordo com o padrão da indústria, como as medidas disponíveis através de “Secure Sockets Layer” (“SSL”), para proteger a confidencialidade e segurança das transações online.</p>
    <h4>Uso de Cookies e Web Beacons</h4>
    <p>De tempos em tempos, quando você visita um website do Wrahgles, informações podem ser colocadas em seu computador de forma a permitir que reconheçamos seu equipamento. As informações normalmente seguem o formato de um arquivo de texto conhecido como cookie. Os cookies são pequenos dados armazenados no disco rígido de seu computador, e não no website. De forma geral, eles permitem a coleta de determinadas informações sobre seu computador, incluindo seu endereço de protocolo de internet (IP), o sistema operacional de seu equipamento, seu tipo de navegador e o endereço de qualquer site referenciado. O uso de cookies tem o objetivo de oferecer benefícios a você, como eliminar a necessidade de digitar sua senha várias vezes durante uma sessão ou a necessidade de redigitar itens incluídos em um carrinho de compras caso você não deseje concluir uma transação em uma única visita. Cookies também são usados para análise de tráfego de website e perfil demográfico anônimo para podermos melhorar nossos serviços.</p>
    <p>O Wrahgles pode usar os chamados web beacons (ou “pixel tags”) relacionados a alguns websites. No entanto, não os utilizamos para identificar usuários individuais pessoalmente. Web beacons são normalmente imagens gráficas que são colocadas em um website e são usados para contar os visitantes de um website e/ou o acesso a determinados cookies. Essa informação é usada para melhorar nossos serviços. Web beacons normalmente não coletam quaisquer informações além daquelas que o seu navegador oferece como parte de qualquer comunicação pela internet. Se você desabilitar os cookies, o web beacon não mais estará apto a rastrear suas atividades específicas. O web beacon pode continuar a coletar informações sobre visitas a partir de seu endereço de IP, mas essas informações não serão mais únicas.</p>
    <p>Se você não desejar receber cookies, ou quiser ser notificado antes que os mesmos sejam colocados em seu computador, você pode configurar seu navegador para fazê-lo, se seu navegador permitir. Lembre-se que se os cookies estiverem desabilitados você pode não conseguir ver algumas partes do site que poderiam aprimorar sua visita. Alguns de nossos parceiros comerciais cujo conteúdo tem link para o ou saindo do nosso site também podem usar cookies ou web beacons. Entretanto, não temos acesso ou controle sobre estes cookies.</p>
    <h4>Seus Direitos</h4>
    <p>Caso você queira saber quais dados pessoais temos sobre você, se você desejar alterar, retificar, tornar anônimo ou excluir qualquer dado pessoal incompleto, incorreto ou desatualizado, se desejar que deixemos de processar seus dados pessoais com o objetivo de enviar materiais promocionais, de marketing direto ou para participação em pesquisa de mercado, ou por qualquer outro motivo legal, você poderá, da maneira apropriada e de acordo com a lei aplicável, exercer tais direitos entrando em contato conosco através dos pontos de contato listados abaixo. Em alguns casos, especialmente se você desejar excluir ou interromper o processamento de seus dados pessoais, isso pode significar que não poderemos continuar a prestar os serviços para você. Incentivamos você a usar as ferramentas de gerenciamento de perfil disponíveis para os objetivos descrito acima, pois as mesmas oferencem acesso direto a seus dados pessoais, permitindo uma gestão eficiente.</p>
    <p>Observe que o Wrahgles pode precisar identificá-lo e solicitar informações adicionais para atender a solicitação acima. Observe também que a lei aplicável pode conter restrições e outras disposições relacionadas a seus direitos.</p>
    <h4>Controlador de seus dados pessoais e informações de contato</h4>
    <p>Além disso, o afiliado Wrahgles que fornece o produto ou serviço pode ser controladora de seus dados pessoais. Você pode descobrir a identidade do controlador e suas informações de contato revisando os termos e condições do serviço específico ou checando as informações de contato fornecidas no(s) website(s) Wrahgles.</p>
    <p>Para assuntos relacionados às práticas do Wrahgles no que se refere à privacidade você também pode entrar em contato conosco através endereço abaixo:</p>
    <h4>Alterações na Política de Privacidade</h4>
    <p>O Wrahgles pode de tempos em tempos alterar esta Política de privacidade ou alterar, modificar ou retirar a permissão de acesso a este site a qualquer tempo, com ou sem aviso prévio. No entanto, se esta Política de Privacidade for alterada de forma significativa, o Wrahgles colocará por 30 dias no início desta Política e na home page do site um aviso informando a mudança. Recomendamos que você releia esta Política de privacidade de tempos em tempos para ser informado sobre qualquer alteração quanto a mesma.</p>
    <p class="link-pol"><a href="<c:url value="/doc/Politica_de_Privacidade_Wrahgles.doc" />">Clique aqui</a> para baixar a Política de Privacidade.</p>
</div>